package com.mscript.parse.misc;

import java.awt.Component;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 * @author Octavian Theodor Nita (https://github.com/octavian-nita)
 * @version 1.0, Oct 27, 2014
 */
public class MScriptTestRig extends javax.swing.JFrame {

    public MScriptTestRig() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JSplitPane mainSplit = new javax.swing.JSplitPane();
        javax.swing.JPanel rightPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane treeScroll = new javax.swing.JScrollPane();
        treeTree = new javax.swing.JTree();
        javax.swing.JSplitPane leftSplit = new javax.swing.JSplitPane();
        javax.swing.JScrollPane errorsScroll = new javax.swing.JScrollPane();
        errorsPane = new javax.swing.JTextPane();
        javax.swing.JTabbedPane srcPane = new javax.swing.JTabbedPane();
        inlineScroll = new javax.swing.JScrollPane();
        inlinePane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MScript Test Rig, v. 0.1");
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        mainSplit.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        mainSplit.setDividerLocation(400);
        mainSplit.setDividerSize(2);
        mainSplit.setResizeWeight(0.5);

        rightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        treeScroll.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        treeScroll.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0), "Parse Tree"));
        treeScroll.setViewportView(treeTree);

        treeTree.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4)));
        treeTree.setAutoscrolls(true);
        treeTree.setSelectionModel(null);
        treeScroll.setViewportView(treeTree);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(treeScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(treeScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
        );

        mainSplit.setRightComponent(rightPanel);

        leftSplit.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        leftSplit.setDividerLocation(350);
        leftSplit.setDividerSize(2);
        leftSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        leftSplit.setResizeWeight(0.5);

        errorsScroll.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        errorsScroll.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0), "Parse Errors"));

        errorsPane.setEditable(false);
        errorsPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        errorsPane.setContentType("text/html"); // NOI18N
        errorsScroll.setViewportView(errorsPane);

        leftSplit.setRightComponent(errorsScroll);

        srcPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        inlineScroll.setBorder(null);

        inlinePane.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        inlineScroll.setViewportView(inlinePane);

        srcPane.addTab("Inline MScript", inlineScroll);

        leftSplit.setLeftComponent(srcPane);

        mainSplit.setLeftComponent(leftSplit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplit, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplit, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Throwable ex) {
            Logger.getLogger(MScriptTestRig.class.getName()).log(Level.WARNING, null, ex);
        }

        Icon empty = new Icon() {

            @Override
            public void paintIcon(Component c, Graphics g, int x, int y) {
                // Do nothing.
            }

            @Override
            public int getIconWidth() {
                return 0;
            }

            @Override
            public int getIconHeight() {
                return 0;
            }
        };
        UIManager.put("Tree.closedIcon", empty);
        UIManager.put("Tree.openIcon", empty);
        UIManager.put("Tree.leafIcon", empty);

        SwingUtilities.invokeLater(() -> {
            new MScriptTestRig().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane errorsPane;
    private javax.swing.JTextPane inlinePane;
    private javax.swing.JScrollPane inlineScroll;
    private javax.swing.JTree treeTree;
    // End of variables declaration//GEN-END:variables
}
